=== PraveenRavipati/MyWork/Java/workspaces/office Java WorkScapces/training/Parsing/bin/com/vl/parsing/sax/examples/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Employees" type="EmployeesType"/>
    <xs:complexType name="EmployeesType">
        <xs:sequence>
            <xs:element name="Employee" type="EmployeeType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="age" type="xs:int"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="role" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== PraveenRavipati/MyWork/Java/workspaces/office Java WorkScapces/training/Parsing/src/com/vl/parsing/sax/examples/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\users\praveen\Desktop\proxml\employee.xsd">
    <Employee id="1">
        <age>29</age>
        <name>Pankaj</name>
        <gender>Male</gender>
        <role>Java Developer</role>
    </Employee>
    <Employee id="2">
        <age>41</age>
        <name>Lisa</name>
        <gender>Female</gender>
        <role>CEO</role>
    </Employee>
    <Employee id="3">
        <age>40</age>
        <name>Tom</name>
        <gender>Male</gender>
        <role>Manager</role>
    </Employee>
    <Employee id="4">
        <age>25</age>
        <name>Meghna</name>
        <gender>Female</gender>
        <role>Manager</role>
    </Employee>
</Employees>
