=== PraveenRavipati/MyWork/Java/jars/Some Examples/XML/dtd/purchaseOrder.dtd
<!ELEMENT purchaseOrder (orderItems,shippingAddress)>
<!ELEMENT orderItems (Item+)>
<!ELEMENT Item (ItemName,Code)>
<!ELEMENT ItemName (#PCDATA)>
<!ELEMENT Code (#PCDATA)>
<!ELEMENT shippingAddress (Name,FatherName,doorNo,street,city,distict,state,country)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT FatherName (#PCDATA)>
<!ELEMENT doorNo (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT distict (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>

=== PraveenRavipati/MyWork/Java/jars/Some Examples/XML/dtd/perchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE purchaseOrder SYSTEM "C:\users\praveen\Desktop\xml\purchaseOrder.dtd">
<purchaseOrder>
	<orderItems>
		<Item>
			<ItemName>lenovo ideaPad z580</ItemName>
			<Code>10101</Code>
		</Item>
		<Item>
			<ItemName>creative SBS A335 speakers</ItemName>
			<Code>10102</Code>
		</Item>
		<Item>
			<ItemName>Lenovo N100 Wireless Mouse</ItemName>
			<Code>10103</Code>
		</Item>
		<Item>
			<ItemName>Ubuntu Edge</ItemName>
			<Code>10104</Code>
		</Item>
	</orderItems>
	<shippingAddress>
		<Name>Srinivas Ravipati</Name>
		<FatherName>Raghuram Ravipati</FatherName>
		<doorNo>12-97</doorNo>
		<street>Main Road</street>
		<city>chirala</city>
		<distict>prakasam</distict>
		<state>andhra pradesh</state>
		<country>india</country>
	</shippingAddress>
</purchaseOrder>
