=== PraveenRavipati/MyWork/Java/jars/Some Examples/XML/XML-Schema/College.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">



<xs:element name="College" type="CollegeType"></xs:element>
<xs:complexType name="CollegeType">
<xs:sequence>
<xs:element name="CollegeDetails" type="CollegeDetailsType"></xs:element>
<xs:element name="Departments" type="DepartmentsType"></xs:element>
<xs:element name="CollegeExaminationCell" type="CollegeExaminationCellType"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="CollegeDetailsType">
<xs:sequence>
<xs:element name="CollName" type="xs:string"></xs:element>
<xs:element name="CollChairManName" type="xs:string"></xs:element>
<xs:element name="CollPrinceName" type="xs:string"></xs:element>
<xs:element name="Estd" type="xs:int"></xs:element>
<xs:element name="CollAddress" type="xs:string"></xs:element>
<xs:element name="CollCity" type="xs:string"></xs:element>
<xs:element name="CollState" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="DepartmentsType">
<xs:sequence>
<xs:element name="Department" type="DepartmentType" minOccurs="1" maxOccurs="unbounded"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="DepartmentType">
<xs:sequence>
<xs:element name="DeptDetails" type="DeptDetailsType"></xs:element>
<xs:element name="DeptStaff" type="DeptStaffType"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="DeptDetailsType">
<xs:sequence>
<xs:element name="DeptName" type="xs:string"></xs:element>
<xs:element name="DeptHOD" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="DeptStaffType">
<xs:sequence>
<xs:element name="Teaching" type="TeachingType"></xs:element>
<xs:element name="Non-Teaching" type="Non-TeachingType"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="TeachingType">
<xs:sequence>
<xs:element name="Professor" type="ProfessorType" maxOccurs="unbounded"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="ProfessorType">
<xs:sequence>
<xs:element name="ProName" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="Non-TeachingType">
<xs:sequence>
<xs:element name="technican" type="technicanType" maxOccurs="unbounded"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="technicanType">
<xs:sequence>
<xs:element name="technicanName" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="CollegeExaminationCellType">
	<xs:sequence>
		<xs:element name="Head" type="HeadType"></xs:element>
		<xs:element name="Staff" type="StaffType" maxOccurs="unbounded"></xs:element>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="HeadType">
<xs:sequence>
<xs:element name="HeadName" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
	<xs:complexType name="StaffType">
		<xs:sequence>
			<xs:element name="StaffName" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== PraveenRavipati/MyWork/Java/jars/Some Examples/XML/XML-Schema/College.xml
<?xml version="1.0" encoding="UTF-8"?>
<College xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\users\praveen\Desktop\xml\XML-Schema\College.xsd">
	<CollegeDetails>
		<CollName>VRS AND YRN COLLEGE OF ENGINEERING AND TECHNOLOGY</CollName>
		<CollChairManName>Sri V. Venkata Rama Chandra Vasu</CollChairManName>
		<CollPrinceName>Dr S. Satyanarayana</CollPrinceName>
		<Estd>1951</Estd>
		<CollAddress>Vaderevu road</CollAddress>
		<CollCity>chiala</CollCity>
		<CollState>Andhra Pradesh</CollState>
	</CollegeDetails>
	<Departments>
		<Department>
			<DeptDetails>
				<DeptName>Computer Science</DeptName>
				<DeptHOD>Srinivas Rao garu</DeptHOD>
			</DeptDetails>
			<DeptStaff>
				<Teaching>
					<Professor>
						<ProName>Rama Krishna garu</ProName>
					</Professor>
					<Professor>
						<ProName>Uma Maheswarao garu</ProName>
					</Professor>
					<Professor>
						<ProName>Sri Devi garu</ProName>
					</Professor>
					<Professor>
						<ProName>Sree Latha garu</ProName>
					</Professor>
					<Professor>
						<ProName>Padmavathi garu</ProName>
					</Professor>
				</Teaching>
				<Non-Teaching>
					<technican>
						<technicanName>Mallikarjun</technicanName>
					</technican>
					<technican>
						<technicanName>Kiran</technicanName>
					</technican>
				</Non-Teaching>
			</DeptStaff>
		</Department>
	</Departments>
	<CollegeExaminationCell>
		<Head>
			<HeadName>Subba rao garu</HeadName>
		</Head>
		<Staff>
			<StaffName>Phani garu</StaffName>
		</Staff>
		<Staff>
			<StaffName>Srinivas garu</StaffName>
		</Staff>
		<Staff>
			<StaffName>Raghavendra garu</StaffName>
		</Staff>
	</CollegeExaminationCell>
</College>
