<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees [ 
<!ELEMENT Employees (Employee+)>
<!ELEMENT Employee (age,name,gender,role)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT role (#PCDATA)>

<!ATTLIST Employee id CDATA #REQUIRED>
]>
<Employees>
    <Employee id="1">
        <age>29</age>
        <name>Pankaj</name>
        <name>rajeev</name>
        <gender>Male</gender>
        <role>Java Developer</role>
    </Employee>
    <Employee id="2">
        <age>25</age>
        <name>Lisa</name>
        <gender>Female</gender>
        <role>CEO</role>
    </Employee>
    <Employee id="3">
        <age>40</age>
        <name>Tom</name>
        <gender>Male</gender>
        <role>Manager</role>
    </Employee>
    <Employee id="4">
        <age>25</age>
        <name>Meghna</name>
        <gender>Female</gender>
        <role>Manager</role>
    </Employee>
</Employees>
